<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Program;
use Illuminate\Support\Str;

class ProgramSeeder extends Seeder
{
    public function run(): void
    {
        $programs = [
            [
                'title' => 'Web Development Bootcamp',
                'discription' => 'Comprehensive web development program covering frontend and backend technologies including HTML, CSS, JavaScript, React, Node.js, and database management.',
                'date' => '2025-11-15',
                'location' => 'Riyadh Tech Center',
                'country' => 'Saudi Arabia',
                'category' => 'Technology',
                'program_coordinatior_name' => 'Dr. Ahmed Al-Rashid',
                'program_coordinatior_phone' => '+966501234567',
                'program_coordinatior_email' => 'ahmed.alrashid@techcenter.sa',
                'enable_qr_attendance' => true,
                'generate_certificates' => true,
                'program_status' => 'active',
                'start_date' => '2025-11-10',
                'end_date' => '2025-12-10',
                'qr_url' => url("/api/v1/programs/qr/" . Str::random(32)),
            ],
            [
                'title' => 'Data Science Workshop',
                'discription' => 'Advanced data science workshop covering machine learning, statistical analysis, and data visualization using Python and R.',
                'date' => '2025-12-01',
                'location' => 'Jeddah Innovation Hub',
                'country' => 'Saudi Arabia',
                'category' => 'Data Science',
                'program_coordinatior_name' => 'Dr. Sarah Al-Mansouri',
                'program_coordinatior_phone' => '+966501234568',
                'program_coordinatior_email' => 'sarah.almansouri@innovation.sa',
                'enable_qr_attendance' => true,
                'generate_certificates' => true,
                'program_status' => 'active',
                'start_date' => '2025-11-25',
                'end_date' => '2025-12-25',
                'qr_url' => url("/api/v1/programs/qr/" . Str::random(32)),
            ],
            [
                'title' => 'Digital Marketing Masterclass',
                'discription' => 'Complete digital marketing course covering SEO, social media marketing, content creation, and analytics.',
                'date' => '2025-12-15',
                'location' => 'Dammam Business Center',
                'country' => 'Saudi Arabia',
                'category' => 'Marketing',
                'program_coordinatior_name' => 'Ms. Fatima Al-Zahra',
                'program_coordinatior_phone' => '+966501234569',
                'program_coordinatior_email' => 'fatima.alzahra@business.sa',
                'enable_qr_attendance' => false,
                'generate_certificates' => true,
                'program_status' => 'active',
                'start_date' => '2025-12-10',
                'end_date' => '2026-01-10',
                'qr_url' => null,
            ],
            [
                'title' => 'Cybersecurity Fundamentals',
                'discription' => 'Essential cybersecurity training covering network security, ethical hacking, and security best practices.',
                'date' => '2025-11-20',
                'location' => 'Riyadh Security Institute',
                'country' => 'Saudi Arabia',
                'category' => 'Security',
                'program_coordinatior_name' => 'Eng. Khalid Al-Shehri',
                'program_coordinatior_phone' => '+966501234570',
                'program_coordinatior_email' => 'khalid.alshehri@security.sa',
                'enable_qr_attendance' => true,
                'generate_certificates' => false,
                'program_status' => 'active',
                'start_date' => '2025-11-15',
                'end_date' => '2025-12-15',
                'qr_url' => url("/api/v1/programs/qr/" . Str::random(32)),
            ],
            [
                'title' => 'Mobile App Development',
                'discription' => 'Comprehensive mobile app development course covering React Native, Flutter, and native iOS/Android development.',
                'date' => '2025-12-05',
                'location' => 'Jeddah Mobile Lab',
                'country' => 'Saudi Arabia',
                'category' => 'Mobile Development',
                'program_coordinatior_name' => 'Mr. Omar Al-Mutairi',
                'program_coordinatior_phone' => '+966501234571',
                'program_coordinatior_email' => 'omar.almutairi@mobile.sa',
                'enable_qr_attendance' => true,
                'generate_certificates' => true,
                'program_status' => 'inactive',
                'start_date' => '2025-11-30',
                'end_date' => '2026-01-30',
                'qr_url' => url("/api/v1/programs/qr/" . Str::random(32)),
            ],
            [
                'title' => 'AI and Machine Learning',
                'discription' => 'Advanced artificial intelligence and machine learning program covering deep learning, neural networks, and AI applications.',
                'date' => '2025-11-25',
                'location' => 'Riyadh AI Center',
                'country' => 'Saudi Arabia',
                'category' => 'Artificial Intelligence',
                'program_coordinatior_name' => 'Dr. Noura Al-Dosari',
                'program_coordinatior_phone' => '+966501234572',
                'program_coordinatior_email' => 'noura.aldosari@ai.sa',
                'enable_qr_attendance' => true,
                'generate_certificates' => true,
                'program_status' => 'completed',
                'start_date' => '2025-11-20',
                'end_date' => '2025-12-20',
                'qr_url' => url("/api/v1/programs/qr/" . Str::random(32)),
            ],
            [
                'title' => 'Cloud Computing Workshop',
                'discription' => 'Cloud computing fundamentals covering AWS, Azure, and Google Cloud Platform services and deployment strategies.',
                'date' => '2025-12-10',
                'location' => 'Dammam Cloud Academy',
                'country' => 'Saudi Arabia',
                'category' => 'Cloud Computing',
                'program_coordinatior_name' => 'Eng. Majed Al-Ghamdi',
                'program_coordinatior_phone' => '+966501234573',
                'program_coordinatior_email' => 'majed.alghamdi@cloud.sa',
                'enable_qr_attendance' => false,
                'generate_certificates' => false,
                'program_status' => 'cancelled',
                'start_date' => '2025-12-05',
                'end_date' => '2026-01-05',
                'qr_url' => null,
            ],
            [
                'title' => 'Blockchain Technology',
                'discription' => 'Comprehensive blockchain and cryptocurrency course covering smart contracts, DeFi, and blockchain development.',
                'date' => '2025-12-20',
                'location' => 'Riyadh Blockchain Hub',
                'country' => 'Saudi Arabia',
                'category' => 'Blockchain',
                'program_coordinatior_name' => 'Dr. Abdullah Al-Rashid',
                'program_coordinatior_phone' => '+966501234574',
                'program_coordinatior_email' => 'abdullah.alrashid@blockchain.sa',
                'enable_qr_attendance' => true,
                'generate_certificates' => true,
                'program_status' => 'active',
                'start_date' => '2025-12-15',
                'end_date' => '2026-02-15',
                'qr_url' => url("/api/v1/programs/qr/" . Str::random(32)),
            ]
        ];

        foreach ($programs as $programData) {
            Program::create($programData);
        }
    }
}
