<?php

echo "📋 COMPLETE API ENDPOINTS GUIDE\n";
echo "===============================\n\n";

echo "🔐 ADMIN ENDPOINTS (Require Admin Authentication)\n";
echo "=================================================\n\n";

echo "1️⃣ CREATE PROGRAM\n";
echo "POST /api/v1/admin/programs\n";
echo "Headers: Authorization: Bearer {admin_token}\n";
echo "Headers: Content-Type: application/json\n\n";
echo "Request Body:\n";
echo "{\n";
echo "  \"title\": \"Web Development Workshop\",\n";
echo "  \"discription\": \"Learn modern web development\",\n";
echo "  \"date\": \"2025-11-15\",\n";
echo "  \"location\": \"Tech Center\",\n";
echo "  \"country\": \"Saudi Arabia\",\n";
echo "  \"category\": \"Workshop\",\n";
echo "  \"program_coordinatior_name\": \"John Doe\",\n";
echo "  \"program_coordinatior_phone\": \"+966501234567\",\n";
echo "  \"program_coordinatior_email\": \"coordinator@example.com\",\n";
echo "  \"start_date\": \"2025-11-10\",\n";
echo "  \"end_date\": \"2025-11-20\",\n";
echo "  \"enable_qr_attendance\": true,\n";
echo "  \"generate_certificates\": true\n";
echo "}\n\n";
echo "Expected Response (201 Created):\n";
echo "{\n";
echo "  \"message\": \"Program created successfully\",\n";
echo "  \"program\": {\n";
echo "    \"program_id\": 1,\n";
echo "    \"title\": \"Web Development Workshop\",\n";
echo "    \"discription\": \"Learn modern web development\",\n";
echo "    \"date\": \"2025-11-15T00:00:00.000000Z\",\n";
echo "    \"location\": \"Tech Center\",\n";
echo "    \"country\": \"Saudi Arabia\",\n";
echo "    \"category\": \"Workshop\",\n";
echo "    \"qr_url\": \"http://127.0.0.1:8000/api/v1/programs/qr/abc123token\",\n";
echo "    \"program_coordinatior_name\": \"John Doe\",\n";
echo "    \"program_coordinatior_phone\": \"+966501234567\",\n";
echo "    \"program_coordinatior_email\": \"coordinator@example.com\",\n";
echo "    \"enable_qr_attendance\": true,\n";
echo "    \"generate_certificates\": true,\n";
echo "    \"program_status\": \"active\",\n";
echo "    \"start_date\": \"2025-11-10T00:00:00.000000Z\",\n";
echo "    \"end_date\": \"2025-11-20T00:00:00.000000Z\",\n";
echo "    \"created_at\": \"2025-10-22T04:04:07.000000Z\",\n";
echo "    \"updated_at\": \"2025-10-22T04:04:07.000000Z\"\n";
echo "  }\n";
echo "}\n\n";

echo "2️⃣ GET ALL PROGRAMS\n";
echo "GET /api/v1/admin/programs\n";
echo "Headers: Authorization: Bearer {admin_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"programs\": [\n";
echo "    {\n";
echo "      \"program_id\": 1,\n";
echo "      \"title\": \"Web Development Workshop\",\n";
echo "      \"discription\": \"Learn modern web development\",\n";
echo "      \"date\": \"2025-11-15T00:00:00.000000Z\",\n";
echo "      \"location\": \"Tech Center\",\n";
echo "      \"country\": \"Saudi Arabia\",\n";
echo "      \"category\": \"Workshop\",\n";
echo "      \"enable_qr_attendance\": true,\n";
echo "      \"generate_certificates\": true,\n";
echo "      \"program_status\": \"active\",\n";
echo "      \"program_applications_count\": 5\n";
echo "    }\n";
echo "  ]\n";
echo "}\n\n";

echo "3️⃣ GET SPECIFIC PROGRAM\n";
echo "GET /api/v1/admin/programs/{id}\n";
echo "Headers: Authorization: Bearer {admin_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"program\": {\n";
echo "    \"program_id\": 1,\n";
echo "    \"title\": \"Web Development Workshop\",\n";
echo "    \"discription\": \"Learn modern web development\",\n";
echo "    \"date\": \"2025-11-15T00:00:00.000000Z\",\n";
echo "    \"location\": \"Tech Center\",\n";
echo "    \"country\": \"Saudi Arabia\",\n";
echo "    \"category\": \"Workshop\",\n";
echo "    \"qr_url\": \"http://127.0.0.1:8000/api/v1/programs/qr/abc123token\",\n";
echo "    \"program_coordinatior_name\": \"John Doe\",\n";
echo "    \"program_coordinatior_phone\": \"+966501234567\",\n";
echo "    \"program_coordinatior_email\": \"coordinator@example.com\",\n";
echo "    \"enable_qr_attendance\": true,\n";
echo "    \"generate_certificates\": true,\n";
echo "    \"program_status\": \"active\",\n";
echo "    \"start_date\": \"2025-11-10T00:00:00.000000Z\",\n";
echo "    \"end_date\": \"2025-11-20T00:00:00.000000Z\",\n";
echo "    \"program_applications\": []\n";
echo "  }\n";
echo "}\n\n";

echo "4️⃣ UPDATE PROGRAM\n";
echo "PUT /api/v1/admin/programs/{id}\n";
echo "Headers: Authorization: Bearer {admin_token}\n";
echo "Headers: Content-Type: application/json\n\n";
echo "Request Body (Any combination of fields):\n";
echo "{\n";
echo "  \"title\": \"Updated Workshop Title\",\n";
echo "  \"discription\": \"Updated description\",\n";
echo "  \"date\": \"2025-12-01\",\n";
echo "  \"location\": \"Updated Location\",\n";
echo "  \"country\": \"Saudi Arabia\",\n";
echo "  \"category\": \"Updated Workshop\",\n";
echo "  \"program_coordinatior_name\": \"Updated Coordinator\",\n";
echo "  \"program_coordinatior_phone\": \"+966501234567\",\n";
echo "  \"program_coordinatior_email\": \"updated@example.com\",\n";
echo "  \"start_date\": \"2025-12-01\",\n";
echo "  \"end_date\": \"2025-12-31\",\n";
echo "  \"program_status\": \"inactive\",\n";
echo "  \"enable_qr_attendance\": false,\n";
echo "  \"generate_certificates\": true\n";
echo "}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"message\": \"Program updated successfully\",\n";
echo "  \"program\": {\n";
echo "    \"program_id\": 1,\n";
echo "    \"title\": \"Updated Workshop Title\",\n";
echo "    \"discription\": \"Updated description\",\n";
echo "    \"date\": \"2025-12-01T00:00:00.000000Z\",\n";
echo "    \"location\": \"Updated Location\",\n";
echo "    \"country\": \"Saudi Arabia\",\n";
echo "    \"category\": \"Updated Workshop\",\n";
echo "    \"program_coordinatior_name\": \"Updated Coordinator\",\n";
echo "    \"program_coordinatior_phone\": \"+966501234567\",\n";
echo "    \"program_coordinatior_email\": \"updated@example.com\",\n";
echo "    \"enable_qr_attendance\": false,\n";
echo "    \"generate_certificates\": true,\n";
echo "    \"program_status\": \"inactive\",\n";
echo "    \"start_date\": \"2025-12-01T00:00:00.000000Z\",\n";
echo "    \"end_date\": \"2025-12-31T00:00:00.000000Z\",\n";
echo "    \"updated_at\": \"2025-10-22T07:26:45.000000Z\"\n";
echo "  }\n";
echo "}\n\n";

echo "5️⃣ DELETE PROGRAM\n";
echo "DELETE /api/v1/admin/programs/{id}\n";
echo "Headers: Authorization: Bearer {admin_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"message\": \"Program deleted successfully\"\n";
echo "}\n\n";

echo "6️⃣ CHANGE PROGRAM STATUS\n";
echo "PATCH /api/v1/admin/programs/{id}/status\n";
echo "Headers: Authorization: Bearer {admin_token}\n";
echo "Headers: Content-Type: application/json\n\n";
echo "Request Body:\n";
echo "{\n";
echo "  \"program_status\": \"completed\"\n";
echo "}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"message\": \"Program status updated successfully\",\n";
echo "  \"program\": {\n";
echo "    \"program_id\": 1,\n";
echo "    \"title\": \"Web Development Workshop\",\n";
echo "    \"program_status\": \"completed\",\n";
echo "    \"...\": \"...\"\n";
echo "  }\n";
echo "}\n\n";

echo "7️⃣ GET PROGRAM STATISTICS\n";
echo "GET /api/v1/admin/programs/statistics\n";
echo "Headers: Authorization: Bearer {admin_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"statistics\": {\n";
echo "    \"total_programs\": 10,\n";
echo "    \"active_programs\": 5,\n";
echo "    \"completed_programs\": 3,\n";
echo "    \"cancelled_programs\": 2,\n";
echo "    \"total_applications\": 25,\n";
echo "    \"pending_applications\": 5,\n";
echo "    \"approved_applications\": 20\n";
echo "  }\n";
echo "}\n\n";

echo "8️⃣ CREATE STUDENT\n";
echo "POST /api/v1/admin/students\n";
echo "Headers: Authorization: Bearer {admin_token}\n";
echo "Headers: Content-Type: application/json\n\n";
echo "Request Body:\n";
echo "{\n";
echo "  \"email\": \"student@example.com\",\n";
echo "  \"password\": \"password123\"\n";
echo "}\n\n";
echo "Expected Response (201 Created):\n";
echo "{\n";
echo "  \"message\": \"Student created successfully\",\n";
echo "  \"student\": {\n";
echo "    \"student_id\": 1,\n";
echo "    \"user_id\": 5,\n";
echo "    \"email\": \"student@example.com\",\n";
echo "    \"role\": \"student\"\n";
echo "  }\n";
echo "}\n\n";

echo "9️⃣ GET ALL STUDENTS\n";
echo "GET /api/v1/admin/students\n";
echo "Headers: Authorization: Bearer {admin_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"students\": [\n";
echo "    {\n";
echo "      \"student_id\": 1,\n";
echo "      \"user_id\": 5,\n";
echo "      \"email\": \"student@example.com\",\n";
echo "      \"role\": \"student\",\n";
echo "      \"ar_name\": null,\n";
echo "      \"en_name\": null,\n";
echo "      \"nationality\": null,\n";
echo "      \"created_at\": \"2025-10-22T04:04:07.000000Z\"\n";
echo "    }\n";
echo "  ]\n";
echo "}\n\n";

echo "🔟 GET SPECIFIC STUDENT\n";
echo "GET /api/v1/admin/students/{id}\n";
echo "Headers: Authorization: Bearer {admin_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"student\": {\n";
echo "    \"student_id\": 1,\n";
echo "    \"user_id\": 5,\n";
echo "    \"email\": \"student@example.com\",\n";
echo "    \"role\": \"student\",\n";
echo "    \"ar_name\": null,\n";
echo "    \"en_name\": null,\n";
echo "    \"nationality\": null,\n";
echo "    \"phone\": null,\n";
echo "    \"passport_number\": null,\n";
echo "    \"date_of_birth\": null,\n";
echo "    \"created_at\": \"2025-10-22T04:04:07.000000Z\"\n";
echo "  }\n";
echo "}\n\n";

echo "1️⃣1️⃣ INVITE STUDENTS TO PROGRAM (Single or Multiple)\n";
echo "POST /api/v1/admin/programs/{programId}/invite\n";
echo "Headers: Authorization: Bearer {admin_token}\n";
echo "Headers: Content-Type: application/json\n\n";
echo "Request Body (Single Student):\n";
echo "{\n";
echo "  \"student_ids\": [1]\n";
echo "}\n\n";
echo "Request Body (Multiple Students):\n";
echo "{\n";
echo "  \"student_ids\": [1, 2, 3]\n";
echo "}\n\n";
echo "Expected Response (201 Created):\n";
echo "{\n";
echo "  \"message\": \"Invitations sent successfully\",\n";
echo "  \"invited_count\": 3,\n";
echo "  \"already_invited_count\": 0,\n";
echo "  \"applications\": [\n";
echo "    {\n";
echo "      \"application_program_id\": 1,\n";
echo "      \"student_id\": 1,\n";
echo "      \"program_id\": 1,\n";
echo "      \"application_status\": \"invite\"\n";
echo "    }\n";
echo "  ],\n";
echo "  \"already_invited_student_ids\": []\n";
echo "}\n\n";

echo "1️⃣2️⃣ GET PROGRAM APPLICATIONS\n";
echo "GET /api/v1/admin/programs/{programId}/applications\n";
echo "Headers: Authorization: Bearer {admin_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"applications\": [\n";
echo "    {\n";
echo "      \"application_program_id\": 1,\n";
echo "      \"student_id\": 1,\n";
echo "      \"program_id\": 1,\n";
echo "      \"application_status\": \"accepted\",\n";
echo "      \"student\": {\n";
echo "        \"student_id\": 1,\n";
echo "        \"en_name\": \"John Doe\",\n";
echo "        \"user\": {\n";
echo "          \"email\": \"student@example.com\"\n";
echo "        }\n";
echo "      }\n";
echo "    }\n";
echo "  ]\n";
echo "}\n\n";

echo "1️⃣3️⃣ APPROVE STUDENT EXCUSE\n";
echo "PATCH /api/v1/admin/applications/{applicationId}/approve-excuse\n";
echo "Headers: Authorization: Bearer {admin_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"message\": \"Student excuse approved successfully\",\n";
echo "  \"application\": {\n";
echo "    \"application_program_id\": 1,\n";
echo "    \"application_status\": \"approved_excuse\",\n";
echo "    \"student_id\": 1,\n";
echo "    \"program_id\": 1\n";
echo "  }\n";
echo "}\n\n";

echo "1️⃣4️⃣ REJECT STUDENT EXCUSE\n";
echo "PATCH /api/v1/admin/applications/{applicationId}/reject-excuse\n";
echo "Headers: Authorization: Bearer {admin_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"message\": \"Student excuse rejected successfully\",\n";
echo "  \"application\": {\n";
echo "    \"application_program_id\": 1,\n";
echo "    \"application_status\": \"doesn_attend\",\n";
echo "    \"student_id\": 1,\n";
echo "    \"program_id\": 1\n";
echo "  }\n";
echo "}\n\n";

echo "👨‍🎓 STUDENT ENDPOINTS (Require Student Authentication)\n";
echo "=====================================================\n\n";

echo "1️⃣5️⃣ ACCEPT INVITATION\n";
echo "PATCH /api/v1/student/applications/{applicationId}/accept\n";
echo "Headers: Authorization: Bearer {student_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"message\": \"Invitation accepted successfully\",\n";
echo "  \"application\": {\n";
echo "    \"application_program_id\": 1,\n";
echo "    \"application_status\": \"accepted\",\n";
echo "    \"student_id\": 1,\n";
echo "    \"program_id\": 1\n";
echo "  }\n";
echo "}\n\n";

echo "1️⃣6️⃣ REJECT INVITATION WITH EXCUSE\n";
echo "PATCH /api/v1/student/applications/{applicationId}/reject\n";
echo "Headers: Authorization: Bearer {student_token}\n";
echo "Headers: Content-Type: multipart/form-data\n\n";
echo "Request Body (form-data):\n";
echo "  excuse_reason: I have a medical appointment\n";
echo "  excuse_file: [FILE_UPLOAD] (optional)\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"message\": \"Invitation rejected with excuse successfully\",\n";
echo "  \"application\": {\n";
echo "    \"application_program_id\": 1,\n";
echo "    \"application_status\": \"excuse\",\n";
echo "    \"excuse_reason\": \"I have a medical appointment\",\n";
echo "    \"excuse_file\": \"excuses/abc123.pdf\",\n";
echo "    \"student_id\": 1,\n";
echo "    \"program_id\": 1\n";
echo "  }\n";
echo "}\n\n";

echo "1️⃣7️⃣ GET MY APPLICATIONS\n";
echo "GET /api/v1/student/applications\n";
echo "Headers: Authorization: Bearer {student_token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"applications\": [\n";
echo "    {\n";
echo "      \"application_program_id\": 1,\n";
echo "      \"application_status\": \"accepted\",\n";
echo "      \"program\": {\n";
echo "        \"program_id\": 1,\n";
echo "        \"title\": \"Web Development Workshop\",\n";
echo "        \"date\": \"2025-11-15T00:00:00.000000Z\",\n";
echo "        \"location\": \"Tech Center\"\n";
echo "      }\n";
echo "    }\n";
echo "  ]\n";
echo "}\n\n";

echo "🌐 PUBLIC ENDPOINTS (No Authentication Required)\n";
echo "===============================================\n\n";

echo "1️⃣8️⃣ SCAN QR CODE\n";
echo "GET /api/v1/programs/qr/{token}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"message\": \"QR code scanned successfully\",\n";
echo "  \"program\": {\n";
echo "    \"program_id\": 1,\n";
echo "    \"title\": \"Web Development Workshop\",\n";
echo "    \"date\": \"2025-11-15T00:00:00.000000Z\",\n";
echo "    \"location\": \"Tech Center\",\n";
echo "    \"qr_token\": \"abc123token\"\n";
echo "  }\n";
echo "}\n\n";

echo "1️⃣9️⃣ QR ATTENDANCE (Authenticated)\n";
echo "POST /api/v1/programs/qr/{token}/attendance\n";
echo "Headers: Authorization: Bearer {student_token}\n";
echo "Headers: Content-Type: application/json\n\n";
echo "Request Body:\n";
echo "{\n";
echo "  \"student_id\": 1\n";
echo "}\n\n";
echo "Expected Response (200 OK):\n";
echo "{\n";
echo "  \"message\": \"Attendance marked successfully\",\n";
echo "  \"application\": {\n";
echo "    \"application_program_id\": 1,\n";
echo "    \"application_status\": \"attend\",\n";
echo "    \"student_id\": 1,\n";
echo "    \"program_id\": 1\n";
echo "  },\n";
echo "  \"student\": {\n";
echo "    \"student_id\": 1,\n";
echo "    \"name\": \"John Doe\",\n";
echo "    \"email\": \"student@example.com\"\n";
echo "  }\n";
echo "}\n\n";

echo "❌ ERROR RESPONSES\n";
echo "==================\n\n";

echo "401 Unauthorized:\n";
echo "{\n";
echo "  \"message\": \"Unauthenticated\"\n";
echo "}\n\n";

echo "403 Forbidden:\n";
echo "{\n";
echo "  \"message\": \"Only admins can create programs\"\n";
echo "}\n\n";

echo "404 Not Found:\n";
echo "{\n";
echo "  \"message\": \"Program not found\"\n";
echo "}\n\n";

echo "422 Validation Error:\n";
echo "{\n";
echo "  \"message\": \"The given data was invalid.\",\n";
echo "  \"errors\": {\n";
echo "    \"title\": [\"The title field is required.\"],\n";
echo "    \"date\": [\"The date field must be a valid date.\"]\n";
echo "  }\n";
echo "}\n\n";

echo "500 Server Error:\n";
echo "{\n";
echo "  \"message\": \"Failed to create program\",\n";
echo "  \"error\": \"Database connection failed\"\n";
echo "}\n\n";

echo "✅ ALL 19 ENDPOINTS READY FOR TESTING!\n";
echo "Use these endpoints with proper authentication tokens! 🚀\n\n";
